print('        *******VIDEO AULA 07 ******* ')
print('======= EXECICIOS DA VIDEO AULA 07 =======')
nome = input('Qual é o seu nome ?')
#print('Prazer em te conhecer {} !'.format(nome))
print('Prazer em te conhecer ! {:=^20}'.format(nome))
print('Prazer em te conhecer ! {:<20}'.format(nome))
print('Prazer em te conhecer ! {:>20}'.format(nome))
print('Prazer em te conhecer ! {:^20}'.format(nome))
print('Prazer em te conhecer ! {:20}'.format(nome))
