print('======= DESAFIO 15 AULA 07 =======')
print('ESCREVA UM PROGRAMA QUE PERGUNTE A QUANTIDADE DE KM PECORRIDOS POR UM CARRO ALUGADO E A QUANTIDADE DE DIAS \nPELO QUAIS ELE FICOU ALUGADO. CALCULE O PREÇO A PAGAR, SABENDO QUE O CARRO CUSTA R$ 60,00 POR DIA\nE R$ 0,15 POR KM RODADO.')
car = float(input('QUANTIDADE DE DIAS : '))
km = float(input('QUANTIDADE DE KM RODADOS : '))
d = (60 * car)
r = (km * 0.15)
t = d + r
print('TOTAL A PAGAR DE DIAS R$: {:.2f}\nTOTAL DE A PAGAR KM RODADO R$: {:.2f}\nTOTAL DO SERVIÇO A SE PAGO R$: {:.2f}'.format(d,r,(r + d)))
