print('======== DESAFIO 11 AULA 07 =======')
print('FAÇA UM PROGRMA QUE LEIA A LARGURA E A ALTURA DE PAREDE EM METROS, CALCULE A SUA ÁREA\nE A QUANTIDADE DE TINTA NECESSARIA PARA PINTAR SABENDO QUE CADA LITRO DE TINTA, PINTA UMA AREA DE 2M².')
alt = float(input('CALCULANDO A AREA EM M² E A QUANTIDADE DE TINTA EM LITROS\nALTURA DA PAREDE = '))
larg = float(input('LARGURA DA PAREDE = '))
area = alt * larg
tinta = area / 2
print('AREA DA PAREDE = {}m²\nQUANTIDADE DE TINTA = {}l'.format(area,tinta))
