print('======= DESAFIO 10 AULA 07=======')
print('CRIE UM PROGRAMA QUE LEIA QUANTO UMA PESSOA TEM NA CARTEIRA E MOSTRE QUANTOS DOLARES ELA PODE COMPRAR .\nCONCIDERANDO  USS 1,00= R$3,27')
c = float(input('VALOR NA CARTEIRA R$ = '))
d = float(input('VALOR DO DOLAR EM RELAÇÃO AO REAL USS = '))
r = c / d
print('O VALOR QUE CONTEM NA SUA CARTEIRA É DE R$ {}\nCORRESPONDE A USS {:.2f}'.format(c,r))