import math
print('FAÇA UM PROGRAMA QUE LEIA O COMPRIMENTO DO CATETO OPOSTO E DO CATETO ADJACENTE\nDE UM TRIANGULO RETANGULO. CALCULE E MOSTRE O COMPRIMENTO DA HIPOTENUSA.')
oposto = float(input('COMPRIMENTO DO CATETO OPOSTO : '))
adja = float(input('COMPRIMENTO DO CATETO ADJACENTE : '))
hip = math.hypot(oposto, adja)
print('O VALOR DA HIPOTENUSA {}'.format(hip))